<?php

namespace AppBundle\Repository;

/**
 * ModelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
