<?php

namespace AppBundle\Repository;

/**
 * PostSelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostSelectionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneActiveByOrderId($orderId)
	{
		return $this->createQueryBuilder('ps')
			->where('ps.isActive = 1')
			->andWhere('ps.orderId = :orderId')
				->setParameter('orderId', $orderId)
			->getQuery()->getOneOrNullResult();
	}
	
	public function findSelections()
	{
		$results = $this->createQueryBuilder('ps')
			->where('ps.isActive = 1')
			->orderBy('ps.orderId', 'ASC')
			->getQuery()->getResult();
		
		$selections = array();
		foreach($results As $result){
			$selections[$result->getOrder()] = $result;
		}
		
		return $selections;
	}
}
