<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function findRecents()
	{
		$now = \date('Y-m-d H:i:s');
		return $this->createQueryBuilder('p')
			->where('p.publishedAt IS NOT NULL')
			->andWhere('p.publishedAt <= :now')
				->setParameter('now', $now)
			->orderBy('p.publishedAt', 'DESC')
			->addOrderBy('p.id', 'DESC')
			->setMaxResults(4)
			->getQuery()->getResult();
	}
}
