<?php

namespace AppBundle\Repository;

/**
 * SocialTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialTypeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllWithoutIds($ids)
	{
		$qb = $this->createQueryBuilder('st');
		$qb->where('st.id NOT IN(:ids)')
		   ->setParameter('ids', implode(',', $ids));

		return $qb->getQuery()
			  ->getResult();
	}
}
