<?php

namespace AppBundle\Repository;

/**
 * SocialTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialTypeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllWithoutIds($ids)
	{
		$qb = $this->createQueryBuilder('st');
		if(count($ids) > 0) {
			$qb->where($qb->expr()->notIn('st.id', $ids));
		}
		$qb->orderBy('st.id', 'ASC');

		return $qb->getQuery()
			  ->getResult();
	}
}
