services:
    app.user.factory:
      class: AppBundle\Entity\UserFactory
    app.about.factory:
      class: AppBundle\Entity\AboutFactory
    app.setting.factory:
      class: AppBundle\Entity\SettingFactory
    app.photo_uploader:
        class: AppBundle\FileUploader